spring:
  application:
    name: CRUD-MySQL_6

  datasource:
    url: jdbc:mysql://localhost:3306/crud6
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
